# Generated by Django 3.2.18 on 2023-04-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlgorithmResultsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('algorithmname', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('mae', models.FloatField()),
                ('mse', models.FloatField()),
                ('rmse', models.FloatField()),
                ('r_squared', models.FloatField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AlgorithmResults',
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loginid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserRegistrations',
            },
        ),
        migrations.CreateModel(
            name='UserSearchTweetsLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetid', models.IntegerField()),
                ('username', models.CharField(max_length=250)),
                ('userscreenname', models.CharField(max_length=250)),
                ('tweettext', models.CharField(max_length=1500)),
                ('createdat', models.DateTimeField()),
                ('address', models.CharField(max_length=250, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('userloc', models.IntegerField()),
            ],
            options={
                'db_table': 'TweetsTable',
            },
        ),
    ]
